BBC RSS Feed Application/BBC RSS Feed Application/Models/FeedBBC.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Xml.Linq;

namespace BBC_RSS_Feed_Application.Models
{
    public class FeedBBC
    {
        public string Title {get; set;}
        public string Description { get; set;}
        public string Link { get; set;}
        public string PubDate { get; set;}
    }

    public class ReadFeedBBC
    {
        public static List<FeedBBC> GetFeed()
        {
            var client = new WebClient();
            client.Headers.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
            var xmlData = client.DownloadString("http://feeds.bbci.co.uk/news/uk/rss.xml?edition=uk");

            XDocument xml = XDocument.Parse(xmlData);

            

            var BBCUpdates = (from story in xml.Descendants("item")
                              select new FeedBBC
                              {
                                  Title = ((string)story.Element("title")),
                                  Description = ((string)story.Element("description")),
                                  Link = ((string)story.Element("link")),
                                  PubDate = ((string)story.Element("pubDate"))
                              }).ToList();

            return BBCUpdates;


        }

        public static XDocument GetXML()
        {
            var client = new WebClient();
            client.Headers.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
            var xmlData = client.DownloadString("http://feeds.bbci.co.uk/news/uk/rss.xml?edition=uk");

            XDocument xml = XDocument.Parse(xmlData);

            return xml;


        }
    }
}

BBC RSS Feed Application/BBC RSS Feed Application/Models/IndexAdminBBCFeed.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.IO;
using System.Xml;
using Newtonsoft.Json;
using BBC_RSS_Feed_Application.Models;

namespace BBC_RSS_Feed_Application.Models
{
    public class IndexAdminBBCFeed
    {
        public string Title { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public List<FeedBBC> BBCFeedList { get; set; }
    
        public IndexAdminBBCFeed() {
            XDocument Xdoc = new XDocument();
            Xdoc = ReadFeedBBC.GetXML();
            this.BBCFeedList = new List<FeedBBC>();
            this.Title = Xdoc.Descendants("title").First().Value.ToString();
            this.Link = Xdoc.Descendants("link").First().Value.ToString();
            this.Description = Xdoc.Descendants("description").First().Value.ToString();

            
        }

    }

}

BBC RSS Feed Application/BBC RSS Feed Application/Controllers/RSSFeedBBCController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.IO;
using System.Xml;
using Newtonsoft.Json;
using BBC_RSS_Feed_Application.Models;

namespace BBC_RSS_Feed_Application.Controllers
{
    public class RSSFeedBBCController : Controller
    {
        // GET: RSSFeedBBC
        public ActionResult Index()
        {

            IndexAdminBBCFeed model = new IndexAdminBBCFeed();

            model.BBCFeedList = ReadFeedBBC.GetFeed();
            return View(model);
        
        }

        public ActionResult Save()
        {
            try
            {

                IndexAdminBBCFeed Feed = new IndexAdminBBCFeed();

                Feed.BBCFeedList = ReadFeedBBC.GetFeed();

                Feed = CheckForDuplicates(Feed);

                string jsonText = JsonConvert.SerializeObject(Feed, Newtonsoft.Json.Formatting.Indented);

                string FileName = DateTime.Now.ToString("yyyy-MM-dd-H") + ".json";

                System.IO.File.WriteAllText(@"C:\Users\David\BBCRSSFeedData\" + FileName, jsonText);

                return Json(new { savedOK = true }, JsonRequestBehavior.AllowGet);

            }

            catch
            {
                return Json(new { savedOK = false }, JsonRequestBehavior.AllowGet);
            }
            

        }

        public IndexAdminBBCFeed CheckForDuplicates(IndexAdminBBCFeed Feed) {

            IndexAdminBBCFeed OldFeed = new IndexAdminBBCFeed();

            OldFeed = LoadDayNewsItems();
            NewsItemsComparer NewsComparer = new NewsItemsComparer();

            var FeedList = Feed.BBCFeedList.Except(OldFeed.BBCFeedList, (NewsComparer));

            if (FeedList.FirstOrDefault() == null||FeedList == null|| FeedList.Any(s => string.IsNullOrEmpty(s.Title)))
            {
                FeedList = new List<FeedBBC>();
            }
            Feed.BBCFeedList = FeedList.ToList();
         
            return Feed;

        }

        public IndexAdminBBCFeed LoadDayNewsItems()
        {
            XmlDocument xml = new XmlDocument();

            IndexAdminBBCFeed OldFeed = new IndexAdminBBCFeed();

            foreach (string file in Directory.EnumerateFiles(@"C:\Users\David\BBCRSSFeedData\", "*.json")) 
            {
                string contents = System.IO.File.ReadAllText(file);

                xml = JsonConvert.DeserializeXmlNode(contents, "root");

                XDocument OldDocs = XDocument.Parse(xml.OuterXml);

                List<FeedBBC> BBCUpdates = (from story in OldDocs.Descendants("BBCFeedList")
                                  select new FeedBBC
                                  {
                                      Title = ((string)story.Element("Title")),
                                      Description = ((string)story.Element("Description")),
                                      Link = ((string)story.Element("Link")),
                                      PubDate = ((string)story.Element("PubDate"))
                                  }).ToList();

                OldFeed.BBCFeedList.AddRange(BBCUpdates);

            }


            return OldFeed;
        }
    }

    public class NewsItemsComparer : IEqualityComparer<FeedBBC>
    {
        public bool Equals(FeedBBC x, FeedBBC y)
        {
            return
                x.Title == y.Title &&
                x.Description == y.Description &&
                x.Link == y.Link &&
                x.PubDate == y.PubDate;

            }

        public int GetHashCode(FeedBBC obj)
        {
            if (obj.Title != null)
            {
                return obj.Title.GetHashCode();
            }
            else
            {
                return obj.GetHashCode();
            }
        }
  
    }
}

BBC RSS Feed Application/BBC RSS Feed Application/Views/RSSFeedBBC/Index.cshtml
@model BBC_RSS_Feed_Application.Models.IndexAdminBBCFeed


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home - BBC RSS Feed List</title>
</head>
<body>
    <div>
        <h2>Home - BBC RSS Feed List</h2>
        @foreach (var item in Model.BBCFeedList)
        {
            @item.Title.ToString(); <br />
            @item.Description.ToString(); <br />
            @Convert.ToDateTime(item.PubDate) <br />
            <a href="@(item.Link)">@item.Link.ToString();</a> <br />
            <br />
        }
    </div>
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>

    // this function works by checking the minute changed event - used for development as not waiting an hour for the hour changed event...

    @*var minute = moment().minute() + 1;
    var now = null;

    setInterval(function () {
        now = moment().minute();
        if (now === minute) {
            alert("hi, the minute has changed!!!");
            minute = moment().minute() + 1;
            $.ajax({
                url: '@Url.Action("Save", "RSSFeedBBC")',
                success: savedFunction,
                error: errorFunction

            });
        }

    }, 1000);*@


    var hour = moment().hour() + 1;
    var now = null;

    setInterval(function () {
        now = moment().hour();
        if (now === hour) {
            hour = moment().hour() + 1;
            $.ajax({
                url: '@Url.Action("Save", "RSSFeedBBC")',
                dataType: 'JSON',
                success: savedFunction,
                error: errorFunction

            });
        }

    }, 1000);


    function savedFunction(data) {
        if (data.savedOK == true) {
            alert("it saved ok!");
        }
        else {
            alert("save failed!!!");
        }
    }

    function errorFunction(data) {
        alert("save failed!!!");
    }


</script>